### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by bnicenboim** [vansky/neural-complexity#5]
Hi,
I want to try this, but is there an already trained (large-ish) model that would be compatible? 

Bruno

**Comment by vansky** [comment]
Yes! This code should be compatible with other pretrained pytorch LSTMs. Here are a few different options depending on what you need:  
* I pretrained 25 different English LSTMs with 5 replications each on Wikipedia (125 models total)
 [van Schijndel et al (2019) Quantity doesn’t buy quality syntax with neural language models](https://www.aclweb.org/anthology/D19-1592)
https://zenodo.org/record/3559340
* Forrest Davis has released models released 5 models of English and 5 for Spanish (both on Wikipedia)
[Davis and van Schijndel (2020) RNN LMs Always Learn English-Like RC Attachment](https://www.aclweb.org/anthology/2020.acl-main.179/)
https://zenodo.org/record/3778994
* Forrest Davis released 5 models of English discourse-intact LSTMs (as opposed to the more standard isolated-sentence LSTMs found in the other releases)
[Davis and van Schijndel (2020) Interaction with Context During RNN Sentence Processing](https://psyarxiv.com/8r65d/)
https://github.com/forrestdavis/GardenPath/tree/master/models/ordered
* Gulordava et al (2018) released 1 pretrained model trained on 80 million tokens for each of English, Hebrew, Russian, and Italian
[Gulordava et al (2018) Colorless Green Recurrent Networks Dream Hierarchically](https://www.aclweb.org/anthology/N18-1108/)
https://github.com/facebookresearch/colorlessgreenRNNs/tree/master/data

**Comment by vansky** [comment]
I think all of these require checking out a previous version of this repo due to backwards incompatibilities I haven't yet resolved:
`git checkout tags/v1.1.0`
